### ISSUE TITLE
Unable to create a account 

### ISSUE THREAD

**Issue by RG1208** [HarjjotSinghh/avocodos-web#3]
Unable to get verification code on gmail.
If i try to get the code again then the page shows username already taken and if I change the username then it shows the wallet is already linked with some another account.

screenshots:-

![Screenshot 2024-09-01 223009](https://github.com/user-attachments/assets/74a9ef02-5dc0-4ba5-8bd2-b9991a37862b)
![Screenshot 2024-09-01 224028](https://github.com/user-attachments/assets/2037a93a-9b45-4659-80a9-e5dbc2890e35)

**Comment by HarjjotSinghh** [comment]
Hey @RG1208, thanks for raising an issue. The issue seems to be that the email was not verified with the correct on the first time. Only one email and wallet address can be used per account, I will recommend you make another account on your wallet, and connect that when signing up, or if you do not want to create another account then let me know, I will delete your records from our database and then you can re-use any email, username and wallet address.

Thanks.

**Comment by HarjjotSinghh** [comment]
@RG1208 please let me know if the issue resolved so that I can close the issue. Thanks once again.

**Comment by RG1208** [comment]
> @RG1208 please let me know if the issue resolved so that I can close the issue. Thanks once again.

Yes you can now close this issue 
I have logged in with some another id
